### ISSUE TITLE
Enable setting the hostName as the ipAddress

### ISSUE THREAD

**Issue by shaileshfsr** [jquatier/eureka-js-client#104] opened 2017-01-19 02:27 UTC
Spring Cloud Eureka client configuration allows using the IP Address of the host to be used as the host name rather than the hostname that is by default assigned. This is particularly helpful in AWS environments where the hostname is not in many cases resolvable by your DNS server. E.g. the default host name that AWS assigns is of the type ip-XX-XX-XX-XX and this many times does not resolved depending on how your DNS is configured

Spring Cloud supplies a config parameter preferIpAddress which is by default false and when set to true will use the local-ipv4 / public-ipv4 instead of local-hostname / public-hostname attributes from the EC2 metadata. 

Can we add this feature since without this we are unable to use the module in our environment. I will be happy to work on this and issue a pull request

**Comment by jquatier** [comment] 2017-01-19 03:49
Hey @shaileshfsr, Thanks for the report. I just put in a PR to add this since it was a minor change. Feel free to take a look. Once the code is reviewed we'll get a new version published.

**Comment by ransikafs** [comment] 2017-01-19 18:11
Hi @jquatier Thanks for a great library. Currently we are having Spring and NodeJS base micro services app which has a Spring API Gateway (written in Java). The Gateway can access the Java base micro services through Feign client without any problem.

But when trying to access the NodeJS based micro service, we always get "Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: MEMBER-SERVICE"

The Node-Eureka client is 4.1.4 and has the following settings:
const EUREKA_CLIENT = new EUREKA({
  instance: {
    app: config.application_identifier,
    //hostName: config.server_name, 
    //ipAddr: '127.0.0.1',
    vipAddress: 'test.something.com',
    statusPageUrl: 'http://__HOST__:30043/',
    healthCheckUrl: 'http://__HOST__:30043/healthcheck',
    preferIpAddress : true,
    port: {
      '$': port,
      '@enabled': 'true',
    },
    secureVipAddress: config.application_identifier,
    /*dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    }*/
     dataCenterInfo: {
      '@class': 'com.netflix.appinfo.AmazonInfo',
      name: 'Amazon',
    }
  },

But as you can see based on the image of eureka, it's still having the local host name as apposed to the local IP. The concern is, since preferIpAddress is not getting set, the local host name is used, thus the server can't be resolved?

![issue](https://cloud.githubusercontent.com/assets/20202478/22119220/b9a6ab1e-dea0-11e6-8e30-5f989956094c.png)

Appreciate if you can give us an input on this. Again, thanks a lot for the hard work.

**Comment by jquatier** [comment] 2017-01-19 18:30
@ransikafs The PR hasn't be merged yet, so the `preferIpAddress` option will not work since the code is not there. We'll publish a new version today so that you can upgrade your `package.json` to use it.

**Comment by ransikafs** [comment] 2017-01-19 18:57
@jquatier thank you so much.

**Closed** 2017-01-20 01:36 UTC

**Comment by jquatier** [comment] 2017-01-20 01:40
`preferIpAddress` option is now available in v4.2.0

**Comment by ransikafs** [comment] 2017-01-20 03:17
@jquatier Thank you so much. I am going to try it now.

**Comment by ransikafs** [comment] 2017-01-20 07:28
@jquatier I have added the preferIpAddress attribute and the eureka registers with the local IP. But unfortunately, I still get the same error
"Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: MEMBER-SERVICE"

<img width="1280" alt="screen shot 2017-01-20 at 12 58 33 pm" src="https://cloud.githubusercontent.com/assets/20202478/22140014/e4b69c6e-df0f-11e6-9ee2-792eccd1b5a1.png">

The same gateway works perfectly with the Java services we have. Tried with multiple nodejs services, all of the node services have the same issue.

I have fetchRegistry=true on the API gateway side.

I would be very thankful if you can give me a hint/tip to fix this issue.

Regards,

**Comment by jquatier** [comment] 2017-01-20 07:44
@ransikafs Looks like the eureka client is working correctly and registering the application, so that's good from this modules perspective. One thing I noticed in your screenshot is that you are still registering with a `vipAddress` of "test-something.com" which seems to be just copy paste from my example code. If your Spring API gateway is using vip addresses to look up instances, this could be the cause of your issues. I would try changing the `vipAddress` to member-service as well. Or, look up what your Java services are registering with as their `vipAddress` and match that. Keep in mind that it could take a minute or so for the load balancer (Ribbon) to refresh it's list of instances after your Node application registers.

**Comment by ransikafs** [comment] 2017-01-20 07:51
Wow man, you are the best. It's working perfectly now. Thank you so much.
